In [42]:
from graphMatching import *
from networkx import read_edgelist
from scipy.io import loadmat
from model import *
from utils import *

In [43]:
# import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
from matplotlib.patches import ConnectionPatch

In [44]:
def test_matching(truth, test):
    matching = []
    test = test.tolist()
    truth = truth.tolist()

    for item in test:
        if item in truth:
            matching.append(item)
    return matching

In [45]:
data = "ACM_DBLP" # args.dataset

device = torch.device('cuda:0' if torch.cuda.is_available() else "cpu")
train_features = {}
if (data == "ACM_DBLP"):
    train_set = ["ACM", "DBLP"]
    input_dim = 17
    b = np.load('data/ACM-DBLP.npz')
    train_features["ACM"] = [torch.from_numpy(b["x1"]).float()]
    train_features["DBLP"] = [torch.from_numpy(b["x2"]).float()]
    test_pairs = b['test_pairs'].astype(np.int32)
    NUM_HIDDEN_LAYERS = 12
    HIDDEN_DIM = 1024
    output_feature_size = 1024
    lr = 0.0001
    epoch = 100
elif (data == "Douban Online_Offline"):
    a1, f1, a2, f2, test_pairs = load_douban()
    f1 = f1.A
    f2 = f2.A
    train_set = ["Online", "Offline"]
    input_dim = 538
    test_pairs = torch.tensor(np.array(test_pairs, dtype=int)) - 1
    test_pairs = test_pairs.numpy()
    train_features["Online"] = [torch.from_numpy(f1).float()]
    train_features["Offline"] = [torch.from_numpy(f2).float()]
    NUM_HIDDEN_LAYERS = 6
    HIDDEN_DIM = 512
    output_feature_size = 512
    lr = 0.0001
    epoch = 100


In [46]:
""" temp = torch.from_numpy(b["x1"]).float() # G1, features
print(temp.shape)
temp """

' temp = torch.from_numpy(b["x1"]).float() # G1, features\nprint(temp.shape)\ntemp '

In [47]:
""" temp = torch.from_numpy(b["x2"]).float() # G2, features
print(temp.shape)
temp """

' temp = torch.from_numpy(b["x2"]).float() # G2, features\nprint(temp.shape)\ntemp '

In [48]:
""" temp = b["test_pairs"]
print(temp.shape)
temp """

' temp = b["test_pairs"]\nprint(temp.shape)\ntemp '

In [49]:
test_pairs

array([[   0, 6829],
       [   2, 3102],
       [   3, 3584],
       ...,
       [9841, 3392],
       [9850,  306],
       [9868, 9011]], dtype=int32)

In [50]:
train_set

['ACM', 'DBLP']

In [51]:
encoder = "GIN"
use_input_augmentation = True
use_output_augmentation = False
print("Loading training datasets")
train_loader = {}
for dataset in train_set:
    train_loader[dataset] = [load_adj(dataset)]

train_loader

Loading training datasets


{'ACM': [tensor([[0., 1., 1.,  ..., 0., 0., 0.],
          [1., 0., 1.,  ..., 0., 0., 0.],
          [1., 1., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]])],
 'DBLP': [tensor([[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]])]}

In [52]:
train_loader.keys()

dict_keys(['ACM', 'DBLP'])

In [53]:
""" temp = train_loader["ACM"][0]
print(temp.shape)
temp """

' temp = train_loader["ACM"][0]\nprint(temp.shape)\ntemp '

In [54]:
""" temp = train_loader["DBLP"][0]
print(temp.shape)
temp """

' temp = train_loader["DBLP"][0]\nprint(temp.shape)\ntemp '

In [55]:
model = GAE(NUM_HIDDEN_LAYERS,
            input_dim,
            HIDDEN_DIM,
            output_feature_size, activation=F.relu,
            use_input_augmentation=use_input_augmentation,
            use_output_augmentation=use_output_augmentation,
            encoder=encoder).to(device)
model

GAE(
  (base_gcn): GIN(
    (in_proj): Linear(in_features=17, out_features=1024, bias=True)
    (convs): ModuleList(
      (0-13): 14 x GINConv(
        (linear): Linear(in_features=1041, out_features=1024, bias=True)
      )
    )
    (out_proj): Linear(in_features=15360, out_features=1024, bias=True)
  )
)

In [56]:
print("Generating training features")


Generating training features


In [57]:
print("Fitting model")
# fit_GAE_real(data, len(train_set) * (1 + 1), model, epoch, train_loader, train_features, device, lr,test_pairs)
# fit_GAE_real(data, no_samples, GAE, epoch, train_loader, train_features, device, lr, test_pairs):

no_samples = len(train_set) * (1 + 1)
GAE = model
# ---

best_hitAtOne = 0
best_hitAtFive = 0
best_hitAtTen = 0
best_hitAtFifty = 0
optimizer = Adam(GAE.parameters(), lr=lr, weight_decay=5e-4)

for step in tqdm(range(epoch)):
    loss = 0
    
    for dataset in train_loader.keys():
        S = train_loader[dataset][0]
        initial_features = train_features[dataset]
        
        for i in range(len(train_loader[dataset])):
            adj_tensor = train_loader[dataset][i]
            adj = coo_matrix(adj_tensor.numpy())
            adj_norm = preprocess_graph(adj)
            pos_weight = float(adj.shape[0] * adj.shape[0] - adj.sum()) / adj.sum()
            norm = adj.shape[0] * adj.shape[0] / float((adj.shape[0] * adj.shape[0] - adj.sum()) * 2)

            adj_label = coo_matrix(S.numpy())
            adj_label = sparse_to_tuple(adj_label)

            adj_norm = torch.sparse.FloatTensor(torch.LongTensor(adj_norm[0].T),
                                                torch.FloatTensor(adj_norm[1]),
                                                torch.Size(adj_norm[2])).to(device)
            adj_label = torch.sparse.FloatTensor(torch.LongTensor(adj_label[0].T),
                                                torch.FloatTensor(adj_label[1]),
                                                torch.Size(adj_label[2])).to(device)

            initial_feature = initial_features[i].to(device)

            weight_mask = adj_label.to_dense().view(-1) == 1
            weight_tensor = torch.ones(weight_mask.size(0))
            weight_tensor[weight_mask] = pos_weight
            weight_tensor = weight_tensor.to(device)
            z = GAE(initial_feature, adj_norm)
            A_pred = torch.sigmoid(torch.matmul(z,z.t()))
            loss += norm * F.binary_cross_entropy(A_pred.view(-1), adj_label.to_dense().view(-1),
                                                        weight=weight_tensor)
    
    optimizer.zero_grad()
    loss = loss / no_samples
    loss.backward()
    optimizer.step()

    # ---
    keys = list(train_loader.keys())
    S1 = train_loader[keys[0]][0]
    S2 = train_loader[keys[1]][0]
    
    adj_S1 = coo_matrix(S1.numpy())
    adj_norm_1 = preprocess_graph(adj_S1)
    adj_norm_1 = torch.sparse.FloatTensor(torch.LongTensor(adj_norm_1[0].T),
                                            torch.FloatTensor(adj_norm_1[1]),
                                            torch.Size(adj_norm_1[2])).to(device)
    adj_S2 = coo_matrix(S2.numpy())
    adj_norm_2 = preprocess_graph(adj_S2)
    adj_norm_2 = torch.sparse.FloatTensor(torch.LongTensor(adj_norm_2[0].T),
                                            torch.FloatTensor(adj_norm_2[1]),
                                            torch.Size(adj_norm_2[2])).to(device)
    if (data == "ACM_DBLP"):
        S1_feat = train_features["ACM"][0]
        S2_feat = train_features["DBLP"][0]
    elif (data == "Douban Online_Offline"):
        S1_feat = train_features["Online"][0]
        S2_feat = train_features["Offline"][0]

    # ---
    S1_emb = GAE(S1_feat.to(device), adj_norm_1).detach()
    S2_emb = GAE(S2_feat.to(device), adj_norm_2).detach()

    D = torch.cdist(S1_emb, S2_emb, 2) # Euclidean distance
    
    if (data == "ACM_DBLP"):
        test_idx = test_pairs[:, 0].astype(np.int32)
        labels = test_pairs[:, 1].astype(np.int32)
    elif (data == "Douban Online_Offline"):
        test_idx = test_pairs[0, :].astype(np.int32)
        labels = test_pairs[1, :].astype(np.int32)
    
    hitAtOne = 0
    hitAtFive = 0
    hitAtTen = 0
    hitAtFifty = 0
    hitAtHundred = 0
    
    # test
    
    for i in range(len(test_idx)): # here
        dist_list = D[test_idx[i]]
        # print(i, test_idx[i], dist_list)
        sorted_neighbors = torch.argsort(dist_list).cpu()
        label = labels[i]
        
        """ if i == 0:
            print(label, sorted_neighbors[0].item(), sorted_neighbors)
            # 6829 6829 tensor([6829, 3102,  601,  ..., 7878, 9701, 2044]) """
        
        for j in range(100):
            if (sorted_neighbors[j].item() == label):
                if (j == 0):
                    hitAtOne += 1
                    hitAtFive += 1
                    hitAtTen += 1
                    hitAtFifty += 1
                    hitAtHundred += 1
                    break
                elif (j <= 4):
                    hitAtFive += 1
                    hitAtTen += 1
                    hitAtFifty += 1
                    hitAtHundred += 1
                    break
                elif (j <= 9):
                    hitAtTen += 1
                    hitAtFifty += 1
                    hitAtHundred += 1
                    break
                elif (j <= 49):
                    hitAtFifty += 1
                    hitAtHundred += 1
                    break
                elif (j <= 100):
                    hitAtHundred += 1
                    break
    
    cur_hitAtOne = hitAtOne / len(test_idx)
    cur_hitAtFive = hitAtFive / len(test_idx)
    cur_hitAtTen = hitAtTen / len(test_idx)
    cur_hitAtFifty = hitAtFifty / len(test_idx)

    if(cur_hitAtOne > best_hitAtOne): best_hitAtOne = cur_hitAtOne
    if (cur_hitAtFive > best_hitAtFive): best_hitAtFive = cur_hitAtFive
    if (cur_hitAtTen > best_hitAtTen): best_hitAtTen = cur_hitAtTen
    if (cur_hitAtFifty > best_hitAtFifty): best_hitAtFifty = cur_hitAtFifty

Fitting model


100%|██████████| 100/100 [05:25<00:00,  3.25s/it]


In [64]:
print("The best results achieved:")
print("Hit@1: ", end="")
print(best_hitAtOne)
print("Hit@5: ", end="")
print(best_hitAtFive)
print("Hit@10: ", end="")
print(best_hitAtTen)
print("Hit@50: ", end="")
print(best_hitAtFifty)

The best results achieved:
Hit@1: 0.7387351778656126
Hit@5: 0.9132411067193675
Hit@10: 0.9517786561264822
Hit@50: 0.9806324110671937


In [65]:
D.shape

torch.Size([9872, 9916])

In [66]:
D

tensor([[18.1876, 19.0532, 17.9709,  ..., 18.4254, 18.0560, 17.9208],
        [16.1168, 15.2768, 15.7032,  ..., 16.3174, 15.9581, 15.8029],
        [21.1922, 21.6910, 21.0044,  ..., 21.3225, 20.9596, 20.9315],
        ...,
        [ 2.3519,  4.3234,  1.1759,  ...,  3.5726,  2.2932,  1.9049],
        [ 2.0501,  4.4289,  1.9376,  ...,  3.5604,  1.7815,  0.4585],
        [ 1.7196,  4.5107,  1.9588,  ...,  3.5422,  1.4545,  1.3193]],
       device='cuda:0')

Truth

In [67]:
print(data)
print(test_pairs.shape)
print(test_pairs)

ACM_DBLP
(5060, 2)
[[   0 6829]
 [   2 3102]
 [   3 3584]
 ...
 [9841 3392]
 [9850  306]
 [9868 9011]]


In [68]:
if (data == "ACM_DBLP"):
    test_pairs_ = test_pairs
elif (data == "Douban Online_Offline"):
    test_pairs_ = test_pairs.T
    
truth = test_pairs_[test_pairs_[:, 1].argsort()]
print(truth.shape)
truth

(5060, 2)


array([[3615,    1],
       [1302,    2],
       [ 466,    3],
       ...,
       [6148, 9907],
       [3826, 9911],
       [7275, 9915]], dtype=int32)

Option 0

In [69]:
def hungarian(D):
    print("0")
    P = torch.zeros_like(D)
    matrix = D.tolist()
    m = Munkres()
    print("1")
    indexes = m.compute(matrix)
    print("2")
    total = 0
    for r, c in tqdm(indexes):
        print(r)
        P[r][c] = 1
        total += matrix[r][c]
    return P.t()

P = hungarian(D)
print(P.shape)
# online_offline: 215m
P

0
1


In [ ]:
P

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [40]:
# save

X = P.cpu().numpy()
np.save("P_hungarian_ACM_DBLP", X)

AttributeError: 'numpy.ndarray' object has no attribute 'cpu'

In [24]:
# load

P = np.load("P_hungarian.npy")
P

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [27]:
# from Hungarian (source code)
option0 = []
m, n = P.shape
for i in range(m):
    for j in range(n):
        if P[i][j] == 1:
            option0.append([j, i]) # S, S_hat
option0 = np.array(option0)
print(len(option0))
option0

1118


array([[2952,    0],
       [3417,    1],
       [2013,    2],
       ...,
       [1010, 1115],
       [2330, 1116],
       [3646, 1117]])

In [28]:
matching = test_matching(truth, option0)
print(len(matching))
print(len(matching) / len(truth))
matching

255
0.22808586762075134


[[2952, 0],
 [3417, 1],
 [2013, 2],
 [1581, 6],
 [1217, 8],
 [963, 21],
 [2254, 26],
 [1662, 29],
 [1563, 44],
 [1348, 46],
 [2538, 49],
 [2072, 50],
 [2399, 57],
 [731, 59],
 [834, 60],
 [341, 64],
 [2516, 68],
 [3274, 70],
 [835, 79],
 [3353, 87],
 [3169, 91],
 [2252, 94],
 [2232, 105],
 [3654, 108],
 [272, 115],
 [275, 117],
 [1672, 118],
 [1673, 122],
 [1945, 129],
 [3492, 134],
 [1378, 136],
 [3191, 145],
 [3034, 155],
 [2955, 162],
 [2275, 167],
 [1553, 168],
 [2186, 170],
 [2343, 176],
 [1510, 180],
 [1126, 190],
 [19, 191],
 [2194, 195],
 [1535, 196],
 [240, 205],
 [3181, 208],
 [2476, 209],
 [2452, 211],
 [942, 223],
 [936, 224],
 [3289, 226],
 [3608, 232],
 [3652, 234],
 [2416, 236],
 [670, 241],
 [1265, 243],
 [727, 252],
 [2972, 258],
 [3313, 268],
 [3673, 269],
 [380, 272],
 [385, 273],
 [2797, 274],
 [3257, 278],
 [2684, 286],
 [2666, 291],
 [1966, 292],
 [1106, 295],
 [1784, 300],
 [320, 303],
 [1251, 308],
 [266, 314],
 [3669, 315],
 [830, 318],
 [2813, 324],
 [1049, 32

Option 1

In [29]:
import numpy as np
from scipy.optimize import linear_sum_assignment

def hungarian_algorithm(cost_matrix):
    # Use the linear_sum_assignment method from scipy
    row_ind, col_ind = linear_sum_assignment(cost_matrix)
    
    # Total cost
    total_cost = cost_matrix[row_ind, col_ind].sum()
    
    # The assignments are returned as (row, col) pairs
    assignments = list(zip(row_ind, col_ind))
    
    return total_cost, assignments

total_cost, assignments = hungarian_algorithm(D.cpu())

In [30]:
option1 = np.array(assignments)
option1 = option1[option1[:, 1].argsort()]
print(option1.shape)
option1

(1118, 2)


array([[2952,    0],
       [3417,    1],
       [2013,    2],
       ...,
       [1010, 1115],
       [2330, 1116],
       [3646, 1117]])

In [32]:
matching = test_matching(truth, option1)
print(len(matching))
print(len(matching) / len(truth))
matching

249
0.22271914132379247


[[2952, 0],
 [3417, 1],
 [2013, 2],
 [1581, 6],
 [1217, 8],
 [963, 21],
 [2254, 26],
 [1662, 29],
 [1563, 44],
 [1348, 46],
 [2538, 49],
 [2072, 50],
 [2406, 54],
 [2399, 57],
 [731, 59],
 [834, 60],
 [341, 64],
 [2516, 68],
 [3274, 70],
 [835, 79],
 [3353, 87],
 [3169, 91],
 [2252, 94],
 [2038, 104],
 [2232, 105],
 [3654, 108],
 [272, 115],
 [275, 117],
 [1672, 118],
 [1673, 122],
 [1945, 129],
 [3492, 134],
 [1378, 136],
 [3191, 145],
 [3034, 155],
 [2275, 167],
 [1553, 168],
 [2186, 170],
 [2343, 176],
 [1510, 180],
 [1126, 190],
 [19, 191],
 [2194, 195],
 [1535, 196],
 [240, 205],
 [3181, 208],
 [2476, 209],
 [2452, 211],
 [942, 223],
 [936, 224],
 [3289, 226],
 [3608, 232],
 [3652, 234],
 [2416, 236],
 [670, 241],
 [1265, 243],
 [727, 252],
 [2972, 258],
 [3313, 268],
 [3673, 269],
 [380, 272],
 [385, 273],
 [2797, 274],
 [3257, 278],
 [2684, 286],
 [2666, 291],
 [1966, 292],
 [1106, 295],
 [1784, 300],
 [320, 303],
 [266, 314],
 [3669, 315],
 [2813, 324],
 [1049, 326],
 [2274, 32

In [ ]:
# build graph
def build_graph(adj_norm):
    edges = adj_norm.coalesce().indices()

    G = nx.from_edgelist(edges.T.cpu().numpy())
    G.remove_edges_from(nx.selfloop_edges(G))
    print(G.number_of_nodes(), G.number_of_edges())

    return G

G1 = build_graph(adj_norm_1)
G2 = build_graph(adj_norm_2)

In [ ]:
pos1 = nx.spring_layout(G1)
pos2 = nx.spring_layout(G2)

In [ ]:
plt.figure(figsize=(16, 8))
ax1 = plt.subplot(1, 2, 1)
plt.title('Graph 1')
nx.draw_networkx(G1, pos=pos1, font_color="w")
ax2 = plt.subplot(1, 2, 2)
plt.title('Graph 2')
nx.draw_networkx(G2, pos=pos2, font_color="w")

# add connections
for i in range(len(matching)):
    con = ConnectionPatch(xyA=pos1[matching[i][0]], xyB=pos2[matching[i][1]], coordsA=ax1.transData, coordsB=ax2.transData, arrowstyle="-", color="green")
    ax2.add_artist(con)
plt.show()

Option 2

In [33]:
import pygmtools as pygm

X = pygm.hungarian(D.cpu().numpy())
print(X.shape)
X

(3906, 1118)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [34]:
indices = []
row, col = X.shape
for i in range(row):
    for j in range(col):
        if X[i][j] == 1:
            indices.append([i, j])
option2 = np.array(indices)
option2 = option2[option2[:, 1].argsort()]
print(option2.shape)
option2

(1118, 2)


array([[ 801,    0],
       [ 427,    1],
       [2072,    2],
       ...,
       [ 583, 1115],
       [1854, 1116],
       [2703, 1117]])

In [35]:
matching = test_matching(truth, option2)
print(len(matching))
print(len(matching) / len(truth))
matching

0
0.0


[]

Option 3

In [36]:
indices = []
for i in range(D.shape[0]):
    dist_list = D[i]
    sorted_neighbors = torch.argsort(dist_list).cpu()
    indices.append([i, sorted_neighbors[0]])

option3 = np.array(indices)
option3 = option3[option3[:, 1].argsort()]
print(option3.shape)
option3

(3906, 2)


array([[2952,    0],
       [3639,    0],
       [2112,    0],
       ...,
       [2046, 1115],
       [1010, 1115],
       [ 529, 1117]])

In [37]:
matching = test_matching(truth, option3)
print(len(matching))
print(len(matching) / len(truth))
matching

313
0.27996422182468694


[[2952, 0],
 [3417, 1],
 [1581, 6],
 [1217, 8],
 [3363, 10],
 [1954, 13],
 [1141, 17],
 [963, 21],
 [2254, 26],
 [165, 33],
 [2350, 37],
 [1337, 42],
 [1563, 44],
 [1348, 46],
 [883, 47],
 [2072, 50],
 [2406, 54],
 [2399, 57],
 [731, 59],
 [834, 60],
 [341, 64],
 [2516, 68],
 [3274, 70],
 [337, 73],
 [3039, 74],
 [835, 79],
 [3353, 87],
 [3169, 91],
 [470, 92],
 [2252, 94],
 [2332, 95],
 [2612, 96],
 [53, 97],
 [64, 101],
 [3776, 106],
 [3488, 110],
 [288, 116],
 [275, 117],
 [1672, 118],
 [1653, 121],
 [85, 126],
 [1945, 129],
 [3492, 134],
 [1378, 136],
 [2047, 137],
 [3191, 145],
 [3576, 150],
 [3034, 155],
 [3437, 161],
 [2955, 162],
 [2953, 164],
 [2275, 167],
 [1553, 168],
 [2186, 170],
 [3340, 171],
 [1538, 173],
 [2343, 176],
 [1510, 180],
 [2678, 186],
 [3816, 187],
 [2199, 189],
 [1126, 190],
 [19, 191],
 [2194, 195],
 [1535, 196],
 [240, 205],
 [233, 206],
 [3181, 208],
 [2452, 211],
 [3462, 215],
 [3358, 218],
 [942, 223],
 [936, 224],
 [3289, 226],
 [121, 231],
 [3608, 232

---

In [ ]:
a = torch.tensor([[0.0,  0.0], [0.0, 1.0], [0.0,  2.0]])
print(a)
b = torch.tensor([[0.0, 1.0 ], [1.0,  1.0]])
print(b)
torch.cdist(a, b, p=2)

In [ ]:
a = torch.tensor([[4.01, 3.0, 2.0, 0.1, 4.0]])
print(a)
torch.argsort(a, dim=1)

In [ ]:
a = np.array([[9, 2, 3],
              [4, 5, 6],
              [7, 0, 5]])

a[a[:, 2].argsort()]
